name = "FCar"
main = "Program.fs"
assets = "assets"
developer = "com.machtan"
version = "1.0.0"
icon = "icon.icns"
authors = ["Jakob Lautrup Nysom", "Stinus MÃ¸hl Thomsen"]

dependencies = [
    "MonoMac",
    "Lidgren.Network",
    "Tao.Sdl",
    "MonoGame.Framework"
]